name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: General build step
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Run tests on PR
        if: github.event_name == 'pull_request'
        run: |
          npm install
          npm test

      - name: Run node script on push
        if: github.event_name == 'push'
        run: |
          scp -i ${{ secrets.SSH_KEY }} satish@192.168.1.71:/home/satish/
          ssh -i ${{ secrets.SSH_KEY }} satish@192.168.1.71 "bash -s" < deploy.sh
         

         



